"""Generate the owner's extraction-validation checklist.

`tasks/02-milestone-1.md` makes owner validation of the records both a
precondition and a Done condition: the owner re-checks record fields **as
facts in the repo** — this artifact exists at this path, these numbers
appear in this file — never as review verdicts.

The checklist is generated rather than written so it cannot drift from the
records, and so the high-leverage marking is *derived* rather than guessed.

The first version of this checklist hand-picked which fields to flag, and
missed eight of the ten fields the committed twins actually mutate —
including the entire technique group, which is the harmful-component-kept
lever the whole M1 finding rests on. A hand-picked set is a guess about
what matters. This one is computed:

    high-leverage  =  every field any twin mutates
                   ∪  every field candidate v0 reads

Those are exactly the fields where an extraction error changes what M1
concludes. A twin's direction claim is void if its mutated field was wrong
in the base record; a v0 score is wrong if a field its mapping reads was
wrong. Everything else can be checked, but an error there costs less.

    uv run python tools/make_validation_checklist.py
"""

from __future__ import annotations

import pathlib
import re
from typing import Any

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
RECORDS = REPO / "cases" / "records"
TWINS = REPO / "cases" / "twins"
DEST = REPO / "runs" / "2026-08-10-extraction-validation" / "checklist.md"

CANDIDATE = REPO / "candidates" / "v0" / "criteria.yaml"


def v0_read_fields() -> dict[str, list[str]]:
    """criterion id -> the fields its mapping declares it reads.

    Derived from the candidate rather than hand-listed. An earlier version
    kept a copy here, and it drifted the moment v0's mapping changed: v0
    stopped reading two configuration fields and the checklist went on
    flagging them as read. A hand-maintained mirror of a machine-readable
    file is a bug waiting for someone to edit one and not the other.
    """
    doc = yaml.safe_load(CANDIDATE.read_text(encoding="utf-8"))
    return {spec["id"]: list(spec.get("reads", [])) for spec in doc["criteria"]}


def twin_mutated_fields() -> dict[str, dict[str, set[str]]]:
    """base_case_id -> field -> the twin ids (of that base) that mutate it.

    Keyed by base case as well as field name. An earlier version keyed by
    field name alone, so a twin of p01 got attributed to every record
    holding a field of that name — p02's `untraceable_number_count` was
    flagged "mutated by p01-t03" even though that twin mutates p01, not
    p02. Found at the M1 owner review (review-m1.md B3).
    """
    out: dict[str, dict[str, set[str]]] = {}
    for path in sorted(TWINS.glob("*.yaml")):
        twin = yaml.safe_load(path.read_text(encoding="utf-8"))["twin"]
        base = twin["base_case_id"]
        per_field = out.setdefault(base, {})
        for entry in twin["diff"]:
            field = entry["field"].removeprefix("fields.").removesuffix(".value")
            per_field.setdefault(field, set()).add(twin["twin_id"])
    return out


def fmt(value: Any) -> str:
    if value is None:
        return "`null`"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, list):
        return ", ".join(f"`{v}`" for v in value) if value else "*(empty list)*"
    return f"`{value}`"


def main() -> int:
    mutated_by_base = twin_mutated_fields()
    mutated_fields_any_base = {f for per_field in mutated_by_base.values() for f in per_field}
    v0_fields = {f for names in v0_read_fields().values() for f in names}
    high = mutated_fields_any_base | v0_fields

    out = [
        "# Extraction validation checklist — p01 and p02",
        "",
        "*Owner task, generated by `tools/make_validation_checklist.py`. Do not edit:",
        "regenerate instead.*",
        "",
        "`tasks/02-milestone-1.md` makes this both a precondition and a Done condition.",
        "The protocol is strict: re-check each field **as a fact in the repo** — *this",
        "artifact exists at this path, these numbers appear in this file*. Never as a",
        "review verdict. Your own peer-review text stays out of this entirely.",
        "",
        "## What this is not",
        "",
        "The schema review already done (which produced the items in",
        "`docs/deferred-to-m2.md`) asked a different question: **can the schema express",
        "what is true?** This asks: **did the extractor record what is actually there?**",
        "A record could be systematically wrong in a way no schema discussion surfaces.",
        "",
        "## How to answer a row",
        "",
        "Open the cited paths in the clone and answer **does the file say this?**",
        "— yes / no / can't tell. Clones are at `clones/p01` and `clones/p02`, pinned",
        "at the commits below.",
        "",
        "**A locator check is not a quality check.** If the cited lines say what the",
        "record claims, the answer is **yes** — even when the artifact they sit in is",
        "broken. A non-executable notebook still *contains* the lines cited. Whether",
        "that artifact works is a different field's job (`headline_numbers_traceable`,",
        "`untraceable_number_count`, `document_code_conflicts`), and if the brokenness",
        "is not captured there, that is a finding worth raising separately.",
        "",
        "Answer **no** when the path does not exist, the lines do not say it, or the",
        "value contradicts what you find.",
        "",
        "## What ⚑ means, and why you can stop after them",
        "",
        "⚑ is **derived, not hand-picked**: it marks every field that a committed twin",
        "mutates, plus every field candidate v0 reads. Those are exactly the fields",
        "where an extraction error changes what M1 concludes — a twin's direction claim",
        "is void if its mutated field was wrong in the base, and a v0 score is wrong if",
        "a field it reads was wrong.",
        "",
        f"**{len(high)} fields are flagged.** If time is short, do those and stop, and",
        "say where you stopped — partial validation with a stated stopping point is",
        "worth more than none.",
        "",
        "Fields mutated by twins, with the twins that depend on them:",
        "",
    ]
    for base in sorted(mutated_by_base):
        for field in sorted(mutated_by_base[base]):
            twins = ", ".join(sorted(mutated_by_base[base][field]))
            out.append(f"- `{field}` (of `{base}`) — {twins}")
    out += ["", "---", ""]

    total = flagged = 0
    for case in ("p01", "p02"):
        doc = yaml.safe_load((RECORDS / f"{case}.yaml").read_text(encoding="utf-8"))
        out += [f"## {case} — commit `{doc['commit']}`", ""]
        case_mutated = mutated_by_base.get(case, {})

        def emit(name: str, node: dict, qualified: str) -> None:
            nonlocal total, flagged
            total += 1
            mark = ""
            if qualified in high or name in high:
                mark, _ = "⚑ ", None
                flagged += 1
            why = []
            if qualified in case_mutated:
                why.append("mutated by " + ", ".join(sorted(case_mutated[qualified])))
            if qualified in v0_fields or name in v0_fields:
                why.append("read by v0")
            suffix = f"  *({'; '.join(why)})*" if why else ""
            ev = ", ".join(f"`{e}`" for e in (node.get("evidence") or [])) or "*(none)*"
            out.append(f"- [ ] {mark}**`{qualified}`** = {fmt(node.get('value'))}{suffix}")
            out.append(f"      - {ev}")

        for name, node in doc["fields"].items():
            if "value" in node:
                emit(name, node, name)
            else:
                out += ["", f"### `{name}`", ""]
                for sub, subnode in node.items():
                    emit(sub, subnode, f"{name}.{sub}")
        out.append("")

    # The owner works this file by hand. Regenerating it would silently
    # discard their answers, which is hours of careful reading against the
    # clones — so refuse, and say what to do instead.
    #
    # The first version of this guard looked only for `- [x]`, and missed a
    # file answered as `- [yes]`. It reported success and destroyed the work.
    # So the test is now "any box that is not empty", which catches every
    # annotation style rather than the one style that was imagined.
    answered = re.compile(r"^- \[(?!\s*\])[^\]]*\]", re.M)
    if DEST.exists() and answered.search(DEST.read_text(encoding="utf-8")):
        print(f"REFUSING to overwrite {DEST.relative_to(REPO)}: it contains answers.")
        print("  Someone is part-way through validating. Regenerating would discard that.")
        print("  If the field set changed, add the new rows by hand, or move the")
        print("  worked copy aside first and merge the answers back.")
        return 1

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {DEST.relative_to(REPO)}")
    print(f"  {total} rows, {flagged} flagged high-leverage")
    print(f"  derived from {len(mutated_fields_any_base)} twin-mutated + {len(v0_fields)} v0-read fields")

    missed = [f for f in mutated_fields_any_base if f not in high]
    print("  ! twin-mutated fields not flagged:", missed) if missed else \
        print("  every twin-mutated field is flagged")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
